version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=library_app
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - library_app_network
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_app
    networks:
      - library_app_network

networks:
  library_app_network:

